{% set name = "sqlalchemy-diff" %}
{% set version = "0.1.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0d83243eadc01e116d8d818b2f20a021b7931f783615f3f62ace3cd1c1f64663

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python
    - six >=1.10.0
    - sqlalchemy-utils >=0.32.4

test:
  imports:
    - sqlalchemydiff

about:
  home: https://github.com/Overseas-Student-Living/sqlalchemy-diff
  license: Apache, Version 2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Compare two database schemas using sqlalchemy.
  doc_url: https://github.com/Overseas-Student-Living/sqlalchemy-diff
  dev_url: https://github.com/Overseas-Student-Living/sqlalchemy-diff

extra:
  recipe-maintainers:
    - chrisjsewell
