{% set name = "github-activity" %}
{% set version = "0.1.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 97f4a2c3f5b2ba7de5821055452e026a0d9561c7943b7b938312a7aa8441c0ad

build:
  number: 0
  entry_points:
    - github-activity = github_activity.cli:main
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - ipython
    - ipywidgets
    - markdown
    - numpy
    - pandas
    - python >=3.6
    - python-dateutil
    - requests

test:
  imports:
    - github_activity
  commands:
    - github-activity --help

about:
  home: "https://jupyter.org/"
  license: BSD-3-Clause
  license_file: LICENSE
  summary: "Grab recent issue/PR activity from a GitHub repository and render it as markdown."

extra:
  recipe-maintainers:
    - chrisjsewell
