{% set name = "aiida-lammps" %}
{% set version = "0.4.0b3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 28d8b56cf1914e50a84a3b9a7cb83f908ac046f270d8b95dcb9a28bd43d9b79e

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  skip: True  # [win or py > 36]

requirements:
  host:
    - pip
    - python
    - reentry >=1.3.0
    - setuptools

  run:
    - aiida-core ==1.0.0b3
    - ase >=3.12.0,<4.0.0
    - dateutils
    - jsonschema
    - numpy
    - packaging
    - python
    - six

test:
  imports:
    - aiida_lammps
    - aiida_lammps.calculations
    - aiida_lammps.calculations.lammps
    - aiida_lammps.common
    - aiida_lammps.data
    - aiida_lammps.data.potential
    - aiida_lammps.parsers
    - aiida_lammps.parsers.lammps
    - aiida_lammps.tests
    - aiida_lammps.tests.input_files
    - aiida_lammps.validation

about:
  home: https://github.com/abelcarreras/aiida-lammps
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: AiiDA plugin for LAMMPS
  doc_url: https://github.com/abelcarreras/aiida-lammps
  dev_url: https://github.com/abelcarreras/aiida-lammps

extra:
  recipe-maintainers:
    - chrisjsewell
