{% set name = "sphinx-autobuild" %}
{% set version = "2020.9.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 4b184a7db893f2100bbd831991ae54ca89167a2b9ce68faea71eaa9e37716aed

build:
  number: 0
  entry_points:
    - sphinx-autobuild = sphinx_autobuild.__main__:main
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - livereload >=2.3.0,<3
    - python >=3.6
    - watchdog >=0.7.1,<0.8

test:
  imports:
    - sphinx_autobuild
  commands:
    - sphinx-autobuild --help

about:
  home: "https://github.com/GaretJax/sphinx_autobuild"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Rebuild Sphinx documentation on changes, with live-reload in the browser."

extra:
  recipe-maintainers:
    - chrisjsewell
